name: dummyapp
base: core20
version: '0.1'
summary: A Qt app to show myself how to create a qt snap/
description: A description of my app

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  dummyapp:
    command: bin/desktop-launch $SNAP/bin/DummyApp
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
    environment:
      QT_QPA_PLATFORM: offscreen
      SNAP_DESKTOP_RUNTIME: $SNAP/usr/lib/x86_64-linux-gnu/qt5/bin
      DISABLE_WAYLAND: 1

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
    stage-packages:
      - libqt5widgets5
      - libqt5core5a
      - libqt5gui5

  dummyapp:
    after: [desktop-qt5]
    plugin: dump
    source: release
    stage:
      - bin/DummyApp
    stage-packages:
      - libqt5widgets5
      - libqt5core5a
      - libqt5gui5
